"""added userposts

Revision ID: 0b3e3bcec0d8
Revises: 5d71f16ad93a
Create Date: 2021-01-13 17:36:26.153973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3e3bcec0d8'
down_revision = '5d71f16ad93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('blogBody', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_posts')
    # ### end Alembic commands ###
