"""Added Friends table

Revision ID: 5d71f16ad93a
Revises: c3e38fc810b0
Create Date: 2021-01-08 13:20:11.400486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d71f16ad93a'
down_revision = 'c3e38fc810b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username1', sa.String(length=200), nullable=True),
    sa.Column('username2', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###
