"""Added email flag

Revision ID: af606f04466a
Revises: 91ccdb9bed53
Create Date: 2021-01-07 00:21:42.107300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af606f04466a'
down_revision = '91ccdb9bed53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('todo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=200), nullable=True),
    sa.Column('complete', sa.BOOLEAN(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('desc', sa.TEXT(), nullable=True),
    sa.CheckConstraint('complete IN (0, 1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###
